import {
	cambodian_children_gifts,
	children_cancer_treatment,
	clean_water_wells,
	education_support,
	emergency_shelter,
	team_1,
	team_2,
	team_3,
	team_4,
	turkey_syria_earthquake,
} from "@/lib/assets";

export const CAMPAIGNS = [
	{
		id: 1,
		title: "Help Turkey and Syria Earthquake Relief Fund",
		description: "Since 2006, SOIL has been working in urban...",
		amountRaised: "85,294",
		goalAmount: "97,000",
		supporters: 10580,
		category: "Medical",
		image: turkey_syria_earthquake,
	},
	{
		id: 2,
		title: "Help Poor Children with Cancer to Access Treatment",
		description: "Two powerful earthquakes struck Turkey and...",
		amountRaised: "62,786",
		goalAmount: "85,000",
		supporters: 3190,
		category: "Medical",
		image: children_cancer_treatment,
	},
	{
		id: 3,
		title: "Provide Gift & food to 700 Cambodian Children",
		description: "This project will support families in rural...",
		amountRaised: "18,382",
		goalAmount: "67,000",
		supporters: 3384,
		category: "Food Security",
		image: cambodian_children_gifts,
	},
	{
		id: 4,
		title: "The Clean Water Wells for Rural Communities",
		description: "Building sustainable water infrastructure for remote...",
		amountRaised: "23,920",
		goalAmount: "56,000",
		supporters: 2456,
		category: "Water & Sanitation",
		image: clean_water_wells,
	},
	{
		id: 5,
		title: "Education Support for Underprivileged Students",
		description: "Providing school supplies and scholarships to children...",
		amountRaised: "43,567",
		goalAmount: "75,000",
		supporters: 1892,
		category: "Education",
		image: education_support,
	},
	{
		id: 6,
		title: "The Emergency Shelter for Homeless Families",
		description: "Creating temporary housing solutions for displaced...",
		amountRaised: "15,230",
		goalAmount: "20,000",
		supporters: 4721,
		category: "Housing",
		image: emergency_shelter,
	},
];

export const TEAM_MEMBERS = [
	{
		id: 1,
		name: "Antonio Roberto",
		position: "Founder Pracima",
		image: team_1,
	},
	{
		id: 2,
		name: "Patrick Geurbette",
		position: "Business Man",
		image: team_2,
	},
	{
		id: 3,
		name: "Issam El Bayed",
		position: "Founder & CEO",
		image: team_3,
	},
	{
		id: 4,
		name: "Yasmine Tano",
		position: "Creative Designer",
		image: team_4,
	},
];
