import Footer from "@/components/layout/footer";
import NavBar from "@/components/layout/navbar";
import type { Metadata } from "next";
import { DM_Serif_Display, Onest } from "next/font/google";
import "../styles/globals.css";

const DMSerifDisplay = DM_Serif_Display({
	variable: "--font-dm-serif-display",
	subsets: ["latin"],
	weight: "400",
});

const onest = Onest({
	variable: "--font-onest",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Olod",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<link
					href="https://cdn.jsdelivr.net/npm/@fontsource/mona-sans@latest/index.css"
					rel="stylesheet"
				/>
			</head>
			<body
				className={`${onest.variable} ${DMSerifDisplay.variable} font-onest antialiased`}
			>
				<NavBar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
